#!/bin/bash
echo "Setting env variables.."
export TURTLEBOT_SENSOR=rplidar_a2
export TURTLEBOT_BASE=kobuki
export TURTLEBOT_STACKS=hexagons
export TURTLEBOT_SERIAL_PORT=/dev/ttyUSB1
export TURTLEBOT_BATTERY=/proc/acpi/battery/BAT0
export TURTLEBOT_SIMULATION=false
export TURTLEBOT_MAP_FILE=/map/0002.yaml

echo "TURTLEBOT_SENSOR: $TURTLEBOT_SENSOR"
echo "TURTLEBOT_BASE: $TURTLEBOT_BASE"
echo "TURTLEBOT_STACKS: $TURTLEBOT_STACKS"
echo "TURTLEBOT_SERIAL_PORT: $TURTLEBOT_SERIAL_PORT"
echo "TURTLEBOT_BATTERY: $TURTLEBOT_BATTERY"
echo "TURTLEBOT_SIMULATION: $TURTLEBOT_SIMULATION"
echo "TURTLEBOT_MAP_FILE: $TURTLEBOT_MAP_FILE"


